import MyNav from "./Navbar";
import { Providers } from "./components/Providers";
import "./globals.css";
import theme from "./theme";
import "./aos.css";
import "./font.css";
import "./body.css";
import Theme from "./blogs/nextTheme";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Theme>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Providers>
              {/* <Navbar /> */}
              <MyNav />
              <main>{children}</main>
            </Providers>
          </ThemeProvider>
        </Theme>
      </body>
    </html>
  );
}
